# Generated by Django 4.2.2 on 2023-07-02 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=100)),
                ('price', models.IntegerField(max_length=50)),
                ('catagory', models.CharField(max_length=100, null=True)),
                ('desc', models.TextField(default='')),
                ('image', models.ImageField(upload_to='static/images')),
            ],
        ),
    ]
