# Generated by Django 4.2.2 on 2023-07-02 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='subcatagory',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
