# Generated by Django 4.2.2 on 2023-07-03 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_catagory_remove_product_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='subcatagory',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='catagory',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Catagory',
        ),
    ]
