# Generated by Django 4.2.2 on 2023-07-03 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_catagory_remove_product_subcatagory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catagory',
            name='sname',
        ),
    ]
